FROM tensorflow/tensorflow:2.1.0-gpu-py3-jupyter

RUN pip3 install jupyter_kernel_gateway jupyterlab

WORKDIR /
ADD requirements.tensorflow.txt requirements.txt
RUN pip3 install -r requirements.txt

ADD tf_startup.sh tf_startup.sh
WORKDIR /ltag
ENV PYTHONPATH=/ltag

CMD ["bash", "/tf_startup.sh"]
