FROM tensorflow/tensorflow:2.0.0-gpu-py3-jupyter

RUN pip3 install jupyter_kernel_gateway jupyterlab

WORKDIR /
ADD requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

ADD tf_startup.sh tf_startup.sh
WORKDIR /ltag

CMD ["bash", "/tf_startup.sh"]
